# -*- after-save-hook: (org-babel-tangle t); -*-
#+TITLE: Linux
#+AUTHOR: Mathieu Marques
#+PROPERTY: header-args :results silent

This file documents the steps I've followed to install my daily machine running
Arch.

* Bootstrap

** X

=~/.xinitrc=

#+BEGIN_SRC sh :shebang "#!/bin/sh" :tangle ~/.xinitrc
# Merge-in defaults and keymaps
userresources=$HOME/.Xresources
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# Start additional programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Bootstrap
xset r rate 200 50
picom &
nitrogen --restore &
qtile start
#+END_SRC

=~/.profile=

#+BEGIN_SRC sh :tangle ~/.profile
# Automatically start X
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
#+END_SRC

Optionally, create a =.zprofile= link to the profile file.

#+BEGIN_SRC sh
ln -s ~/.profile ~/.zprofile
#+END_SRC

=~/.Xresources=

Customize X resources, for =xterm= mostly.

#+BEGIN_SRC conf :tangle ~/.Xresources
XTerm*faceName: monospace:style=Regular
XTerm*faceSize: 14
#+END_SRC

** Core Dependencies and =paru=

#+BEGIN_SRC sh
pacman -S base-devel git
#+END_SRC

Paru is now stable enough that it should be preferred over =yay=.

#+BEGIN_SRC sh
git clone https://aur.archlinux.org/paru.git /tmp/paru
cd /tmp/paru
makepkg -si
#+END_SRC

Customize =/etc/pacman.conf= and enable additional repositories.

#+BEGIN_SRC diff
 [options]
+Color
+IgnorePkg = emacs-git
+ParallelDownloads = 4
+VerbosePkgLists

+[extra]
+Include = /etc/pacman.d/mirrorlist

+[community]
+Include = /etc/pacman.d/mirrorlist

+[multilib]
+Include = /etc/pacman.d/mirrorlist
#+END_SRC

** Visudo

Run =visudo= in order to customize sudoers settings.

*** Change the Default Editor

#+BEGIN_SRC diff
+Defaults editor=/usr/bin/vim
#+END_SRC

*** Enable Asterisks During Password Prompts

#+BEGIN_SRC diff
-Defaults env_reset
+Defaults env_reset,pwfeedback
#+END_SRC

** Node.js

Install the package manager =yarn= and the Node version manager =nvm=.

#+BEGIN_SRC sh
paru -S nvm yarn
#+END_SRC

In order to use =nvm=, source its bootstrap file in your shell configuration.

#+BEGIN_SRC sh
source /usr/share/nvm/init-nvm.sh
#+END_SRC

** Python

Python 3 comes with =venv= to manage virtual environments. For Python 2,
=virtualenv= is required.

#+BEGIN_SRC sh
paru -S python python-virtualenv
#+END_SRC

Then create environments with either =python -m venv name= or =virtualenv name=.

* Shell

** Zsh

See [[./config/zsh.org][config/zsh.org]].

** Terminal

See [[./config/alacritty.org][config/alacritty.org]].

* Fonts

** Font Dependencies

Install my favorite fonts. Other sections from this document will assume these
are already installed.

#+BEGIN_SRC sh
paru -S \
    noto-fonts-emoji \
    otf-code-new-roman \
    ttf-google-sans \
    ttf-monaco \
    ttf-roboto \
    ttf-roboto-slab
#+END_SRC

** Aliasing and Hinting

Enable aliasing and hinting presets.

#+BEGIN_SRC sh
rm -f /etc/fonts/conf.d/10-hinting-slight.conf
ln -s /usr/share/fontconfig/conf.avail/10-hinting-full.conf /etc/fonts/conf.d
ln -s /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf /etc/fonts/conf.d
ln -s /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf /etc/fonts/conf.d
ln -s /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d
#+END_SRC

Uncomment FreeType hinting in =/etc/profile.d/freetype2.sh=.

#+BEGIN_SRC diff
-# export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
+export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
#+END_SRC

** Font Preferences

Set default font for classes in =/etc/fonts/local.conf=.

#+BEGIN_SRC xml :tangle /sudo:://etc/fonts/local.conf
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
  <match target="pattern">
    <test qual="any" name="family">
      <string>serif</string>
    </test>
    <edit name="family" mode="assign" binding="same">
      <string>Roboto Slab</string>
    </edit>
  </match>
  <match target="pattern">
    <test qual="any" name="family">
      <string>sans-serif</string>
    </test>
    <edit name="family" mode="assign" binding="same">
      <string>Google Sans</string>
    </edit>
  </match>
  <match target="pattern">
    <test qual="any" name="family">
      <string>monospace</string>
    </test>
    <edit name="family" mode="assign" binding="same">
      <string>Code New Roman</string>
    </edit>
  </match>
</fontconfig>
#+END_SRC

* Desktop

** Compositor

See [[./config/picom.org][config/picom.org]].

** Theme

*** GTK

#+BEGIN_SRC sh
paru -S lxappearance materia-gtk-theme
#+END_SRC

Enable the theme in GTK settings through =lxappearance= and verify the
configuration file =~/.config/gtk-3.0/settings.ini=.

*** Qt

#+BEGIN_SRC sh
paru -S kvantum-qt5 kvantum-theme-materia
#+END_SRC

Then run =kvantummanager= to select your theme.

** Window Manager

*** Qtile

See [[./config/qtile.org][config/qtile.org]].

*** XMonad

See [[./config/xmonad.org][config/xmonad.org]].

** Notifications

See [[./config/dunst.org][config/dunst.org]].

** Screenshots

#+BEGIN_SRC sh
paru -S ffcast slop xclip
#+END_SRC

Several scripts are available under [[./scripts/][scripts/]].

** Sound

#+BEGIN_SRC sh
paru -S alsa-utils pavucontrol
#+END_SRC

Make sure that the devices are correctly selected in =pavucontrol= and that the
=pulseaudio= server is running.

#+BEGIN_SRC sh
systemctl --user status pulseaudio.service
systemctl --user status pulseaudio.socket
#+END_SRC

Use the following command to detect input sound.

#+BEGIN_SRC sh
arecord -vv -f dat /dev/null
#+END_SRC

* Emacs

Install the preferred =gccemacs=. Details at http://akrl.sdf.org/gccemacs.html.
CMake is necessary in order to compile the dependencies to =vterm= at runtime.

#+BEGIN_SRC sh
paru -S cmake libgccjit noto-fonts-emoji
paru -G emacs-git
#+END_SRC

Edit =emacs-git/PKGBUILD= and enable just-in-time compilation.

#+BEGIN_SRC diff
-JIT=              # Enable native just-in-time compilation. libgccjit is in AUR.
+JIT="YES"         # Enable native just-in-time compilation. libgccjit is in AUR.
#+END_SRC

Install =emacs= with the new flags.

#+BEGIN_SRC sh
cd emacs-git/
makepkg -si
#+END_SRC

See my Emacs configuration: [[https://github.com/angrybacon/dotemacs]].

* Vim

Install =vim= or =gvim=.

#+BEGIN_SRC sh
paru -S vim
#+END_SRC

I mostly use Emacs but sometimes Vim too so very minor tweaks are enough.

#+BEGIN_SRC sh :tangle ~/.vimrc
:syntax on
:set cursorline
#+END_SRC

* Git

=~/.gitconfig=

#+BEGIN_SRC conf :tangle ~/.gitconfig
[user]
    email = mathieumarques78@gmail.com
    name = Mathieu Marques
[core]
    excludesfile = ~/.gitignore
    ignorecase = true
[pull]
    rebase = true
[rebase]
    autosquash = true
#+END_SRC

=~/.gitignore=

#+BEGIN_SRC conf :tangle ~/.gitignore
.dir-locals.el
#+END_SRC

** Signed Commits

1. First generate a key for your machine

   #+BEGIN_SRC sh
   gpg --full-gen-key
   gpg --list-secret-keys --keyid-format LONG <email>
   gpg --armor --export 1234567890ABCDEF
   #+END_SRC

2. Copy the public key to your Git hosting platform

3. Add the secret key to your repository

   #+BEGIN_SRC conf
   [user]
       signingkey = 1234567890ABCDEF
   [commit]
       gpgsign = true
   #+END_SRC

=~./profile=

#+BEGIN_SRC diff
+export GPG_TTY=$TTY
#+END_SRC

* Plex

** Dependencies

Install the server after making sure your DNS settings are correctly set.

#+BEGIN_SRC sh
paru -S plex-media-server
#+END_SRC

** Mounting the External Hard Drive

*** Automatically

#+BEGIN_SRC sh
paru -S udiskie udisks2
#+END_SRC

Start =udiskie= on boot in your =xinit=. It will automatically mount external
drives under =/run/media/username/=. Optionnally keep =udiskie= in the tray with
=--tray=.

*** Manually

Given an external drive named =Phoenix=, create a mount point under =/media= for
the =plex= user to access it.

#+BEGIN_SRC sh
sudo mkdir -p /media/phoenix
sudo chmod -R /media
#+END_SRC

Retrieve the UUID of the drive (with =df= and =blkid= for instance) and add the
corresponding entry at the bottom of =/etc/fstab=.

#+BEGIN_SRC diff
+UUID=1234-ABCD  /media/phoenix  exfat
#+END_SRC

Reboot and confirm that the drive is correctly mounted to the expected location.

** Permissions

First verify which group you and Plex belong to.

#+BEGIN_SRC sh
groups
groups plex
#+END_SRC

Add Plex to a shared group and change the media ownership to match that group.

#+BEGIN_QUOTE
Below instructions assume a setup from =udiskie= defaults where the media is
located under =/run/media/username/=. It also assumes you assume to a =storage=
group. Adjust accordingly.
#+END_QUOTE

#+BEGIN_SRC sh
sudo usermod -a -G storage plex
sudo chown angrybacon:storage /run/media/angrybacon
sudo chmod 750 /run/media/angrybacon
sudo setfacl -m g:storage:rwx /run/media/angrybacon
#+END_SRC

Finally restart the service to apply the new permissions.

#+BEGIN_SRC sh
systemctl restart plexmediaserver.service
#+END_SRC

** Start the Service Automatically on Startup

Enable the server for future sessions automatically and optionally start it now.

#+BEGIN_SRC sh
systemctl start plexmediaserver.service
systemctl enable plexmediaserver.service
#+END_SRC

Visit http://localhost:32400/web and add the media libraries.

** Fix the Claim Server Prompt

This usually happens the preference files don't have the correct permission
and/or ownership.

Confirm the location of the preference files, they should be somewhere in
=/var/lib/plex/=. Then fix the ownership after having stopped the Plex server.

#+BEGIN_SRC sh
sudo chown -R plex:plex /var/lib/plex
#+END_SRC

* SSH

#+BEGIN_SRC sh
paru -S openssh xclip
ssh-keygen -t ed25519
xclip -sel clip < ~/.ssh/id_ed25519.pub
#+END_SRC

* Games

** Battle.net

Battlet.net applications run best under Lutris. It has many dependencies based
on Wine. Follow the instructions at
[[https://github.com/lutris/docs/blob/master/Battle.Net.md]] and install games
from Lutris directly.

#+BEGIN_SRC sh
paru -S lutris
#+END_SRC

** Steam

For Steam games that are officially supported on Linux, install the =steam=
package after enabling =multilib= repositories in your Pacman configuration and
ensuring your graphic drivers are Vulkan-enabled.

#+BEGIN_SRC sh
paru -S steam
#+END_SRC

* Pheripherals

** Video

Use your Android phone as a webcam. It is possible that =linux-headers= should
be installed manually, if so restarting might be necessary.

#+BEGIN_SRC sh
paru -S droidcam v4l2loopback-dkms linux-headers
#+END_SRC

* Other Utilities

#+BEGIN_SRC sh
paru -S \
    discord_arch_electron slack-electron zoom-system-qt \
    cockatrice obs-studio spotify vlc \
    flameshot gimp \
    qbittorrent \
    btop gdu gtop htop piper most tree \
    brave-bin chromium librewolf-bin
#+END_SRC
