# -*- after-save-hook: (org-babel-tangle t); -*-
#+TITLE: Dunst
#+AUTHOR: Mathieu Marques

A default configuration file can be found at
[[https://github.com/dunst-project/dunst]].

#+BEGIN_SRC conf :noweb yes :tangle ~/.config/dunst/dunstrc
[global]
    <<geometry>>
    <<borders>>
    <<idle>>
    <<text>>
    <<actions>>

<<colors>>
#+END_SRC

* Geometry

Set padding for the notifications.

#+BEGIN_SRC conf :noweb-ref geometry
padding = 8                         # Vertical padding in pixels
horizontal_padding = 16             # Horizontal padding in pixels
#+END_SRC

Set size geometry for the notification frame.

#+BEGIN_SRC conf :noweb-ref geometry
height = 300                        # Maximum height for a single notification
width = (200, 800)                  # Dynamic width
#+END_SRC

Add offset to the anchor.

#+BEGIN_SRC conf :noweb-ref geometry
offset = 12x52
origin = top-right
#+END_SRC

* Borders

#+BEGIN_SRC conf :noweb-ref borders
separator_height = 2                # Draw a line between notifications. Set to 0 to disable
frame_color = "#78909C"             # External border color
frame_width = 1                     # border size in pixels. Set to 0 to disable
#+END_SRC

Define the corner radius of the notification window in pixels. If the radius is
0, you have no rounded corners. The radius will be automatically lowered if it
exceeds half of the notification height to avoid clipping text and/or icons.

#+BEGIN_SRC conf :noweb-ref borders
corner_radius = 8
#+END_SRC

* Idle Cleanup

Don't remove messages if the user is idle for longer than =idle_threshold=
seconds. Set to 0 to disable. A client can set the =transient= hint to bypass
this.

#+BEGIN_SRC conf :noweb-ref idle
idle_threshold = 0
#+END_SRC

* Text

#+BEGIN_SRC conf :noweb-ref text
font = Google Sans 16
# word_wrap = yes
#+END_SRC

* Actions

Defines list of actions for each mouse event Possible values are:

- =none=: Don't do anything
- =do_action=: Invoke the action determined by the action_name rule. If there is
  no such action, open the context menu
- =open_url=: If the notification has exactly one url, open it. If there are
  multiple ones, open the context menu
- =close_current=: Close current notification
- =close_all=: Close all notifications
- =context=: Open context menu for the notification
- =context_all=: Open context menu for all notifications

These values can be strung together for each mouse event, and will be executed
in sequence.

#+BEGIN_SRC conf :noweb-ref actions
mouse_left_click = do_action
mouse_middle_click = close_all
mouse_right_click = close_current
#+END_SRC

* Colors

#+BEGIN_SRC conf :noweb-ref colors
[urgency_critical]
    background = "#E53935"
    foreground = "#FAFAFA"
    timeout = 0

[urgency_low]
    background = "#607D8B"
    foreground = "#FAFAFA"
    timeout = 4

[urgency_normal]
    background = "#009688"
    foreground = "#FAFAFA"
    timeout = 8
#+END_SRC
