# -*- after-save-hook: (org-babel-tangle t); -*-
#+TITLE: Picom
#+AUTHOR: Mathieu Marques
#+PROPERTY: header-args:conf :tangle ~/.config/picom/picom.conf

Use a compositor to handle complex graphic interactions eg. dragging,
transparency, shadows.

* Installation

Install =picom= or the preferred fork.

#+BEGIN_SRC sh
paru -S picom
#+END_SRC

To identify the compositor currently running, use =inxi=.

#+BEGIN_SRC sh
inxi -Gxx | grep compositor
#+END_SRC

Start the compositor on login by running =picom= in your =xinit= file. The
=jonaburg= fork will require the =--experimental-backends= flag.

* Configuration

Most of the below configuration comes from the default =/etc/xdg/picom.conf=.

** Backend

Specify the backend to use eg. =xrender=, =glx= or =xr_glx_hybrid=.

#+BEGIN_SRC conf
backend = "glx";
#+END_SRC

** Shadows

Disable all shadows.

Note that desktop windows ie. windows with ='_NET_WM_WINDOW_TYPE_DESKTOP'= never
get shadow, unless explicitly requested using the =wintypes= option.

#+BEGIN_SRC conf
shadow = false;                         # Disable all shadows
#+END_SRC

** Rounded Corners

Only available with =picom-ibhagwan-git=.

#+BEGIN_SRC conf
corner-radius = 16.0;
rounded-corners-exclude = [
  "! name~=''",                         # Exclude windows with no name ie. bars
  "class_i = 'Dunst'",                  # Corners are set in the Dunst configuration
];
round-borders = 1;
round-borders-exclude = [];
#+END_SRC

** Opacity

#+BEGIN_SRC conf
active-opacity = 1.0;
inactive-opacity = .96;
menu-opacity = 1.0                      # Default opacity for dropdowns and popups
#+END_SRC
